Practice/Models/ErrorViewModel.cs
namespace Practice.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Practice/Models/LibraryDB.cs
using Microsoft.EntityFrameworkCore;
namespace Practice.Models
{
    public class LibraryDBContext: DbContext
    {
        public LibraryDBContext(DbContextOptions options) : base(options)
        {

        }
        public DbSet<LibraryData> Librarys { get; set; }
    }
}

Practice/Models/LibraryData.cs
using System.ComponentModel.DataAnnotations;

namespace Practice.Models
{
    public class LibraryData
    {
        [Display(Name="Назва")]
        [Required]
        public string Name { get; set; }
        [Display(Name = "Розташування")]
        [Required]
        public string Place { get; set; }
    }
}

Practice/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Practice.Models;
using System.Diagnostics;

namespace Practice.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Form()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Practice/Controllers/LibraryController.cs
using Microsoft.AspNetCore.Mvc;
using MySqlConnector;
using Practice.Models;
using var connection = new MySqlConnection(" Server=localhost;User ID=root; Password=1111;Database=Library");
namespace Practice.Controllers
{
    public class LibraryController : Controller
    {
        public IActionResult Forms()
        {
            return View();

        }
        public IActionResult Tables()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddLibrary(LibraryData libraryData)
        {
            if(ModelState.IsValid)
            {
                return Redirect("/");
            }
            return View("Forms");
        }
    }
}

Practice/Views/Home/Form.cshtml
@{
    Layout = "_Layout";
}
<div class="row">
    <div class="col-md-6">
        <form>
            <div class="row">
                <div class="col-md-4">
                    <label for="add_library_name">Назва бібліоетки:</label>
                </div>
                <div class="col-md-8">
                    <input type="text" id="add_library_name" name="add_library_name" required>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <label for="add_library_place">Місце бібліоетки:</label>
                    </div>
                    <div class="col-md-8">
                        <input type="text" id="add_library_place" name="add_library_place" required>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

Practice/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Practice/Views/Library/Forms.cshtml
@model LibraryData
@{
    Layout = "_Layout";
}
<div class="row">
    <div class="col-md-6">
        <form method="post" asp-controller="Library" asp-action="AddLibrary">
            <div class="row">
                <div class="col-md-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-md-8">
                    <input asp-for="Name"/>
                    <span asp-validation-for="Name"></span>
                </div>

            </div>
            <div class="row">
                <div class="col-md-4">
                    <label asp-for="Place"></label>
                </div>
                <div class="col-md-8">
                    <input asp-for="Place" />
                    <span asp-validation-for="Place"></span>
                </div>
            </div>
            <input type="submit" value="Send "/>
           
        </form>
    </div>
</div>

Practice/Views/Library/Tables.cshtml
@model LibraryData

@{
    
}



<table class="table">
    <tr>
        <th>Name</th>
        <th>Place</th>
      
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Title)</td>
            <td>@Html.DisplayFor(modelItem => item.Author)</td>
            <td>@Html.DisplayFor(modelItem => item.Year)</td>
        </tr>
    }
</table>

Practice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Practice</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Practice.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Practice</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Library" asp-action="Forms">User Form</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Practice - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>